# Netlify Configuration
[build]
  publish = "build"
  command = "npm run build:prod"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.loanpredict.com wss://api.loanpredict.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy (optional)
[[redirects]]
  from = "/api/*"
  to = "https://api.loanpredict.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "wss://api.loanpredict.com/ws/:splat"
  status = 200
  force = true