model:
  type: gradient_boosting
  random_state: 42
  risk_thresholds:
    low: 0.3
    medium: 0.6
training:
  test_size: 0.2
  cv_folds: 5
  target_column: defaulted
  id_column: application_id
data:
  raw_path: data/raw/loan_applications.csv
  processed_path: data/processed/loan_applications_processed.csv
  feature_store: data/processed/feature_store.csv
artifacts:
  model_path: models/loan_default_model.joblib
  metrics_report: reports/metrics_report.json
  feature_importances: reports/feature_importances.csv
logging:
  level: INFO
  file: logs/app.log
database:
  url: sqlite:///data/loan_risk.db
  echo: false
